source "https://supermarket.chef.io"

cookbook "apt"
cookbook "build-essential"
cookbook "ntp"
cookbook "git"
cookbook "rvm", github: "martinisoft/chef-rvm"
cookbook "dotfiles", path: "~/development/cookbooks/dotfiles"
cookbook "scala"
cookbook "java"
cookbook "simple-scala-sbt"
cookbook "anaconda"
cookbook "anaconda_wrapper", path: "~/development/cookbooks/anaconda_wrapper"
cookbook "omnibus_updater"
cookbook "postgresql"
cookbook "golang"
